### ISSUE TITLE
 Max retries exceeded with url

### ISSUE THREAD

**Issue by jcasta** [mrlt8/docker-wyze-bridge#107]
I keep getting this error on HA addon:

2021/09/07 09:16:14 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/07 09:16:14 [MainThread] HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30fcb81a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Sleeping for 10s...
2021/09/07 09:16:24 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/07 09:16:24 [MainThread] HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30fcb81b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Sleeping for 10s...
2021/09/07 09:16:34 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/07 09:16:34 [MainThread] HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f30fcb81a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Sleeping for 10s...

**Comment by mrlt8** [comment]
Do you have a firewall or dns filter that might be blocking the connection?

**Comment by jmacul2** [comment]
I am having the same issue when installed as a HASS addon.  If I build it manually via docker-compose, everything works.

**Comment by mrlt8** [comment]
Weird. Does restarting HA help?

**Comment by jmacul2** [comment]
No, restarted the server, HA, docker.  Added specific DNS entries to /etc/docker/daemon.json.  Nothing works.  It for sure is a DNS issue.  I can revolve to IP addresses so I know I can get out, but DNS is broken for sure.  /etc/resolve.conf shows:
```
search local.hass.io
nameserver 127.0.0.11
options ndots:0

```
Which essentially mimics /etc/resolve.conf on the Ubuntu host.  My docker must be corked somewhere, but I have quite a few hass addons and all of them resolve fine though DNS so I am confused as to why just this one does not.

**Comment by Echo3ToEcho7** [comment]
I, too, am having this issue. I can resolve and ping from the Terminal & SSH add-on.

**Comment by jun3280net** [comment]
Same issue here (just another data point) - running Home Assistant with Supervisor on a Linux VM.  I am running NGINX Proxy Manager, and recently had to update my config file to address the 400 : Bad Error message that occurs with a more recent HA update.

                http:
                use_x_forwarded_for: true
                trusted_proxies:
                - 127.0.0.1

Log Msg From Addon
2021/09/19 06:53:13 I [0/0] rtsp-simple-server v0.17.3
2021/09/19 06:53:13 I [0/0] [RTSP] TCP listener opened on :8554
2021/09/19 06:53:13 I [0/0] [RTMP] listener opened on :1935
2021/09/19 06:53:13 I [0/0] [HLS] listener opened on :8888
2021/09/19 06:53:13 I [0/0] [API] listener opened on 127.0.0.1:9997

🚀 STARTING DOCKER-WYZE-BRIDGE v0.6.7

🏠 Home Assistant Mode
2021/09/19 06:53:13 [MainThread] 🔍 Could not find local cache for 'user'
2021/09/19 06:53:13 [MainThread] 🔍 Could not find local cache for 'auth'
2021/09/19 06:53:13 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/19 06:53:13 [MainThread] HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faa245e76d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Sleeping for 10s...

**Comment by shizenyasuya** [comment]
I am having this same issue on the latest version using docker-compose.  It worked for me for about a day, but I noticed this morning that my stream had dropped and not come back up for longer than normal, so I checked the container and I had the same errors as OP. I thought it was something to do with the cached information so I re-built docker-compose.yml to add FRESH_DATA to the environment, but it didn't help. I tried re-pulling from the repo in case there was something wyze had changed in the API that broke functionality, but the latest version isn't making any difference.
