### ISSUE TITLE
Configuring on Synology NAS

### ISSUE THREAD

**Issue by dayski8** [mrlt8/docker-wyze-bridge#115]
Hi All, could anyone please show me how to configure wyze-bridge on Synology DSM? Thank you

**Comment by matovey** [comment]
Were you able to figure this out?

**Comment by Viking8** [comment]
Here is a good YouTube video on Synology Docker configuration for Wyze Bridge from Lon.TV https://www.youtube.com/watch?v=lFJyWpa1bo0 
I followed this when he first made the video and it worked perfectly (about 4 months ago), but then my NAS had a massive issue and I had to reinstall DSM. I finally found the time to install it again today with the latest version but the container just keeps restarting. Not sure if it's because the version is so much newer and there's an issue with DSM. Will test and report back.
