### ISSUE TITLE
remember the local IP of camera

### ISSUE THREAD

**Issue by cstout1** [mrlt8/docker-wyze-bridge#167]
Is it possible to have docker-wyze-bridge remember the local IP (statically assigned in my case) of the cameras so that it doesn't need to reach out to wyze and pull the info from the cameras?

My scenario is using NET_MODE=LAN while also prohibiting the cameras access to the internet. I've been successful in establishing the connection with docker-wyze-bridge and then modifying the firewall **after** the connection has started and it will maintain the stream. If I restart the container though, it will then go back to stating the camera is offline:

> Attaching to wyze-bridge
> wyze-bridge    | 🚀 STARTING DOCKER-WYZE-BRIDGE v0.7.6
> ...
> wyze-bridge    | 🎬 STARTING ALL 2 CAMERAS
> wyze-bridge    | 2021/10/08 18:54:17 [WyzeBridge] Starting rtsp-simple-server v0.17.3
> wyze-bridge    | 2021/10/08 18:54:19 [Camera1] IOTC_ER_DEVICE_OFFLINE
> wyze-bridge    | 2021/10/08 18:54:19 [Camera2] IOTC_ER_DEVICE_OFFLINE

If this is something that can be added to the docker-compose file then it could potentially just recall and connect to the specified local IP of the cameras?

**Comment by mrlt8** [comment]
Yes, you should be able to do this by specifying the location where the tokens get saved with something like this:

```yaml
    volumes:
      - ./<local-tokens-dir>:/tokens/
```
where local-tokens-dir is the path where the tokens will be saved outside the container.

**Comment by mrlt8** [comment]
I believe some other users have run into the same [issue](https://github.com/mrlt8/docker-wyze-bridge/issues/121) when trying to block the cameras from the internet.

**Comment by gleep52** [comment]
I seem to have mine working without internet access.  In my compose file  I added: (starting in the environment section under my email/password)

```
            - NET_MODE=LAN
        volumes:
            - ./tokens:/tokens/
```

I had to run it the first time with net_mode=lan hashed out so it would build the files in cache in the tokens folder - then once all cameras were detected and live, I stopped the docker, changed the compose to include the net_mode=lan this time and it finds the static IP cameras, and starts streaming as intended.  I cut off my cameras VLAN from the internet, wyze app no longer works on my phone - restarted docker - cameras spring to life still.

I have four V3 cams on the 4.36.3.19 firmware using the 1.04 build and they seem stable.  I was having issues with the latest build crashing but saw the notes to launch it with FRESH_DATA=true and that seems to have resolved the constant crashing I was seeing.  I was using 0.7.6 as that was the last stable version - but hopefully the fresh_data command does the trick and I'm set again.  :)  

Hope this helps someone!

**Comment by unrly** [comment]
@gleep52 thanks, I had been considering this recently as I've gotten fed up and am about to attempt to run ethernet through my 50 year old house and replace the Wyze with something POE. Has it been running stable for you? Run in to any #211 type of issues?

**Comment by gleep52** [comment]
I hate to bring bad news back - but sadly without the cameras reaching the internet and updating Wyze server's that they are online - they somehow stop streaming, but remain "up" so I can ping them, just no video, if I stop the V3's from having internet access.  I find this absolutely disgusting from Wyze's perspective.  But I don't see a way around it.  I've tried adding all of the camera's communications to a local dns to enable ping uptime connectivity - but it seems the wyze servers somehow are disabling the streams or it's just a random timeout where the cameras stop.  I have two piholes at home and can see all the internet attempts and traffic with my logging - and for some reasons the cameras just stop streaming - probably because they aren't getting the proper communication back from wyze's HQ to keep streaming which is just total BS.  

I absolutely love the video quality and I even have one of my V3's outside on the roof trim which has held up great so far this month with freezing temps.  I plan on playing with it more this week - maybe keep a wireshark going for the camera 24/7 to see what command kills them - but I'm not sure I have the time to do that even on Christmas break :)

For what it's worth - I fell back to 0.7.6 and am still pre-DTLS firmware on my four V3s.  They don't go down at all if I keep the internet active... 

But this kind of programming makes me feel very uneasy that Wyze has specifically coded in an internet uptime method for streaming to even work - are they spying on our cameras?  Why do they care?  Just let it stream internet or not... seems silly.  I mean if the cameras tried to reboot without internet after a specific period of time, I could understand that automation - but they don't reboot - pings stay up all the time.  Kinda creepy.  :(

**Comment by unrly** [comment]
Thanks for the info, I was curious about the communication back to Wyze.

Wyze is nice and cheap and I love the V3 night visibility, but I honestly haven't even had anything remotely reliable in weeks and even took down our most-used cam that constantly had issues as I'm running out of patience trying to get these things to do something they weren't built for.

**Comment by cstout1** [comment]
@gleep52 Any new discoveries with this dumb ping/timeout issue?

I'm really torn on this little camera. It's wonderful for non-security use in its small size and low price, but having a hard requirement for Wyze communication has kept me from buying any more.

My v3 has great day/night quality for $30 and for keeping an eye on kids/pets it's hard to beat.
