### ISSUE TITLE
Where exactly do these .libs come from?

### ISSUE THREAD

**Issue by 8BitAce** [mrlt8/docker-wyze-bridge#272]
I was gifted a Wyze camera and was interested to see how many projects there are for interfacing with them on GitHub.

I noticed though that each one, including this one, have the user install some unexplained libraries onto their system, which is always a red flag to me. I _assume_ they're nothing nefarious, but at the very least would like a bit of info.

From what I can tell I think it's the SDK for tutk? If so, is there anywhere we can download this straight from the manufacturer instead of various GH repos? Especially since googling tutk brings up some unnerving search results about supply chain attacks of their software just earlier this year.

Thanks

**Comment by mrlt8** [comment]
The tutk libraries required to interact with the cameras come from the throughtek kalay sdk which, from what I can tell, used to be available from their site http://www.tutk.com/kalay_kit.html 

I believe you can still request the SDK from tutk, however, the newer versions now require an NDA and key so that's probably why most of the SDKs floating around are from like 2014.

As for the vulnerabilities, I believe they affected the cams on the older SDK which did not use DTLS and an authkey to authenticate connections to the cam.

This project is currently using a modern v4 version of the SDK, but you should be able to drop in your own v3.1.10+ library as long as it has DTLS support.

**Comment by 8BitAce** [comment]
Got it, thanks for the info!
