### ISSUE TITLE
Feature Request: MQTT Status

### ISSUE THREAD

**Issue by Artekus** [mrlt8/docker-wyze-bridge#30]
Would it be possible to add MQTT status for each camera, connected status, open, connections, and maybe even a way for restarting the connection to the cameras as well?

**Comment by mrlt8** [comment]
I personally don't use MQTT, so not very familiar with it, but I could look into it.

**Comment by mrlt8** [comment]
Looking into potentially including some basic MQTT support in the next release.

Any suggestions or requests for the topic structure?

**Comment by Artekus** [comment]
Maybe WyzeBridge as the client name and topic as default like so: `WyzeBridge/Camera_Name(s)/StatusName(s)`  The client and the topic could be environmental variables for docker if someone wants to customize them. Status could be: number of connections, camera state (connected/disconnected), fps, up time, etc. 

If there are options to reset a connection if a camera isn't working or not connecting. Maybe it could be the string "on" sent to `WyzeBridge/Camera_Name(s)/Reconnect` 

Thanks for considering these ideas and great work so far!

**Comment by mrlt8** [comment]
Still having some issues with MQTT images, but the [dev branch](https://github.com/mrlt8/docker-wyze-bridge/tree/dev#mqtt-beta) has some basic MQTT support.

prebuilt images available on `mrlt8/wyze-bridge:dev`

**Comment by WarDrake** [comment]
This is working great, and provides an image, but even tho it also provides a camera entity, there is no video coming through, only the image, was this the intended behaviour? or is something weird going on?

**Comment by mrlt8** [comment]
I believe it's a limitation of the [MQTT Camera](https://www.home-assistant.io/integrations/camera.mqtt/) platform. 

Open to suggestions if anyone knows how to get rtsp over MQTT!

**Comment by DenielTorres** [comment]
Hi @mrlt8! Great work with the MQTT! I was wondering if it would be possible to turn on/off a camera with an MQTT publish. My scenario is that I use a v3 as a baby cam, but obviously I only want the camera on when the kid is asleep. Thanks in advance!

**Comment by mrlt8** [comment]
From what I can tell, the on/off switch in the app doesn't actually turn off the camera but just disables the TUTK server.

I believe the on/off/reboot commands go through the wyze servers, so I don't think there is any way for us to do this on the bridge with our current method since all our commands go directly to the cameras.

However, because of the recent 2FA requirements and changing ENR, we'll probably need to ping the wyze servers more often anyways, so we could probably add more web-api related options like the on/off/reboot at the same time.
