### ISSUE TITLE
WARNINGx3 (looks like frame issue)

### ISSUE THREAD

**Issue by mjb83** [mrlt8/docker-wyze-bridge#339]
Good afternoon,
First off, thank you for this... I've been trying to get a stable wyze bridge going for blue iris forever.. and for 90% of the time its great. I just seem to be having an intermittent disconnect issue which seems to relate to some error messages in the HA log files. I've got 4 wyze cam's running in HA / RTSP. 2 are V2's with no issue, but I'm getting the following from a cam pan and an outdoor:

2022/04/12 12:52:17 [camera] WARNING: Wrong resolution (frame_size=1)
2022/04/12 12:52:17 [camera] WARNING: Requesting frame_size=0 and bitrate=120
2022/04/12 12:52:18 [camera] WARNING: Skipping smaller frame at start of stream (frame_size=1)

I'm getting this from both a cam pan and a cam outdoors. I can't correlate it to any issues with my network (all other devices seem stable when this happens). As mentioned I have two cam V2's that have 100% uptime, no issues.

Anyone seen this before an know how to fix it? I've tried looking for 'frame' type errors here in the other issues reported and I'm not seeing it. My guess is this could be a hardware setting within the camera themselves but I'm hoping its something that I can adjust in either the yaml config for the RTSP output or maybe in blue iris settings. Currently my solution is to restart the bridge in HA when I start seeing these errors.

**Comment by mrlt8** [comment]
Basically, the cameras have two resolutions or "frame_size". HD and SD in the app both use the same 1080p resolution `frame_size=0` with the bitrate set to 120 and 60 respectively. The 360p option in the app uses the other smaller resolution `frame_size=1` with the bitrate set to 30.

The messages you're seeing just indicate that the frame_size received doesn't match what we were expecting, so it either ignores those frames if it's at the start of the stream or sends a request to change it if it happens mid-stream. The camera should then return the correct resolution within a few frames, but may sometimes timeout and cause the connect to the camera to restart.

Since we're using the same stream as the app, any change in frame_size/bitrate in one will reflect in the other. For some reason, the app will sometimes default to opening the stream in 360p which will cause the bridge to show that warning and attempt to correct it.

For the most part, you can just ignore the message since the bridge will attempt to correct it.

**Comment by mjb83** [comment]
OK, makes sense I see the wyze correct for video all the time as well. Just visually different output I suppose.

**Comment by JA16122000** [comment]
I think i have the same problem: https://github.com/mrlt8/docker-wyze-bridge/issues/745
Only no camera will display anything right now
