### ISSUE TITLE
Wyze Outdoor Cam - timeout when connecting

### ISSUE THREAD

**Issue by gitguys** [mrlt8/docker-wyze-bridge#384]
Is this not compatible with a outdoor cam through a base station?

**Comment by mrlt8** [comment]
hmm. Is this the Outdoor v1 or the v2?

**Comment by gitguys** [comment]
> hmm. Is this the Outdoor v1 or the v2?

Doesn't say on the camera. When I do device info through the app it only says "Wyze Cam Outdoor" so I assume it might be v1 because apparently it would say v2 if it was v2.  Would be nice if Wyze would make that more clear.

**Comment by mrlt8** [comment]
Do you see it trying to connect in the bridge's logs? Should look like this:

```
[WyzeBridge] 🎉 Connecting to WyzeCam Outdoor - Driveway on 192.168.200.102 (1/3)
```

**Comment by gitguys** [comment]
Yep, then is times out after 20 seconds.  Then tries again, times out in 20 seconds again.

**Comment by drewski56** [comment]
I can confirm the same timeout issue is happening with my outdoor v1 cams

**Comment by mrlt8** [comment]
Can you guys post the firmware version your Outdoor cams? I'll have to see if they pushed any updates.

**Comment by stephenjlevy** [comment]
I'm seeing the same issue. The 192.168.200.102 address that is trying to be accessed (the same ip that's presented for the camera in the Wyze UI) seems to be assigned internally by the outdoor cam base station, not by my LAN, so it's inaccessible directly from the rest of my network.
Outdoor Cam v1 firmware version: 4.17.4.124
Base station firmware: 4.16.3.117

**Comment by ma-armenta** [comment]
I have the same as @stephenjlevy

**Comment by GJMcClintock** [comment]
Same issue on base firmware 4.16.3.117 and camera firmware 4.17.0.203. Upgraded to 4.17.4.124 anyway to be in line with everybody else here.

Also thought I ordered v2 cameras and thanks to this discovered I actually bought v1 because that's what comes up when you go to their Amazon store. welp.

**Comment by treyallday85** [comment]
Same problem here. I thought I was going crazy until I found this bug listed.

Outdoor Cam v2 - 4.48.4.124
Base Station - 4.16.3.117

**Comment by mrlt8** [comment]
Ok, so it looks like wyze _finally_ updated the outdoor cams to use DTLS!

We just need the new authkey for the camera, so everyone will probably need to do a `FRESH_DATA` on the next release.

**Comment by ma-armenta** [comment]
> Ok, so it looks like wyze _finally_ updated the outdoor cams to use DTLS!
> 
> We just need the new authkey for the camera, so everyone will probably need to do a `FRESH_DATA` on the next release.

What do you mean by running FRESH_DATA?

**Comment by GJMcClintock** [comment]
> What do you mean by need to do a FRESH_DATA?

In the readme it explains it as an env variable you can pass (either add it to the enviornment in your docker-compose, or run `docker-compose up -d -e FRESH_DATA` or similar. It will refresh all your tokens from Wyze instead of reuising the cached API key.

However, you if you run:

```
docker-compose down
docker-compose pull
docker-compose up -d
docker image prune
```

you should be good to go as it will refresh the API key anyway since `down` tears apart your container rather than just stopping it.

**Comment by mrlt8** [comment]
@ma-armenta We need the base station's mac address and ENR, which we weren't saving, to generate the authkey needed to connect to the outdoor cameras.

I made some changes in v1.5.4 so that it will fetch the new data if it can't find it cached locally. No `FRESH_DATA` required.

@treyallday85 Can you confirm if the updates work with the v2?

**Comment by treyallday85** [comment]
Works for me! Thanks.

**Comment by mrlt8** [comment]
Awesome! 

Will mark this issue as resolved for now. Please feel free to open a new issue if you need more assistance!
