### ISSUE TITLE
Bridge does not recognize camera after rename

### ISSUE THREAD

**Issue by Bubbgump209** [mrlt8/docker-wyze-bridge#453]
If a camera is renamed in the Wyze app, it is not recognized by the Bridge and then becomes an orphaned camera. Example -  I had a camera named "Middle bedroom". I moved the camera to the garage and renamed it to "Garage". The camera is not added as Garage and the old Middle Bedroom shows as not available in the Bridge. Expected behavior would be that the bridge simply pulls the current status from the Wyze cloud and changes the name. This is using the Home Assistant Add-on v1.6.8.

**Comment by mrlt8** [comment]
Unfortunately, some other integrations were overwhelming the wyze servers with requests, so wyze placed a rate limit on their web api. 

Most of the data that we need to connect to the cameras remains the same, so we just keep reusing the same old data which is why it wouldn't pickup any of the changes you made. I did run into an issue where one of my cameras was timing out until I did a `FRESH_DATA`, so maybe we could add some logic into the bridge that will 1) keep our session alive to avoid getting locked out of 2fa and 2) refresh the camera data up to once every x hours if it fails to connect? Will have to look into this further.

FYI, while `FRESH_DATA` will pull new data, it will only do so when the container starts, so any changes won't be reflected in the bridge until you restart the container.

**Comment by Bubbgump209** [comment]
I don't know if you need a fix beyond what you have. My mind goes to a few places. "Fix it in the FAQ" aka, make the docs more explicit or indicate stronger the user behavior that is desired. So in my case were there a tool tip to use FRESH_DATA when cameras are added or changed OR a "flush cache and pull new data" button that simply enables FRESH_DATA for a single run would be more than enough. I honestly think the fewer API calls the better lest Wyze get further pissed off and try to limit things in new onerous ways. A manual as needed button with a  good description would be maybe the most effort I would consider.

**Comment by mrlt8** [comment]
Just out of curiosity, I looked up the rate limits for some of the end points that we are using:

```
/user/login
Rate limit: 90
Seconds to reset: 1,500


/user/login/sendSmsCode
Rate limit: 100
Seconds to reset: 300


/app/user/refresh_token
Rate limit: 300
Seconds to reset: 300


/app/user/get_user_info
Rate limit: None
Seconds to reset: None

/app/v2/home_page/get_object_list
Rate limit: 300
Seconds to reset: 300

```
So it would probably be pretty safe to refresh the camera data (one call to `get_object_list` for all cameras) a couple of times an hours.
