### ISSUE TITLE
BOA Server not starting

### ISSUE THREAD

**Issue by exiva** [mrlt8/docker-wyze-bridge#478]
I can't seem to get the BOA server or webhooks to fire. I changed my environment to

```yml
environment:
    - WYZE_EMAIL=foo@bar.baz
    - WYZE_PASSWORD=haxme
    - NET_MODE=LAN
    - ENABLE_BOA=True
    - MOTION_HTTP=http://webhook.lan/event?cam=Back-Yard
```

and when I hover over the Info button, `boa_url` is None, and I'm not getting webhooks on motion. Testing with a v3 cam, has a SD installed in it. 

the camera seem to be connecting in LAN mode, am I missing something?

`2022/07/15 01:10:23 [Back Yard] 📡 Getting 120kb/s HD stream (20fps) via LAN mode (WiFi: 76%) FW: 4.36.9.139 🔒 (DTLS) (2/3)`

Using docker-wyze-bridge v1.7.3. I have a v3 on latest firmware, and a doorbell on latest firmware.

**Comment by mrlt8** [comment]
This seems to be an [known issue](https://forums.wyzecam.com/t/wyze-cameras-no-longer-download-timelapse-videos/221250) with some of the wyze firmware. 

Will try to see if there's a workaround.

**Comment by exiva** [comment]
Oh, okay. So it's unstable & not a good replacement for OpenCV/Pamdiff. Perhaps a note in the docs about it's instability is warranted?

**Comment by mrlt8** [comment]
Not yet. Seems like they're trying to do damage control and kill off boa completely after that article about the "always on" http server even though it was only accessible  with the Timelapse feature.

I've been running the older firmware so didn't notice that they had actually switched to [RDT](http://www.sunipcam.com/sdk/Readme.htm) which was what I initially wanted to use instead of boa since it should theoretically be able to work over P2P mode.

**Comment by dnestico** [comment]
Came to see if I was the only one and yes can confirm no "boa_url" shows for any of my cameras damn.

**Comment by mrlt8** [comment]
Looks like boa was removed from the v3 on v4.36.8.32, so **v4.36.8.26** should theoretically work. 

Firmware **v4.9.8.1002** for the v2 still seems to support boa as well as support for RDT.

**Comment by dnestico** [comment]
Both my V2s and V3s are on the latest beta firmware so (except one has RTSP firmware) so guess I won't be able to use the boa server damn.

**Comment by mrlt8** [comment]
```
https://download.wyzecam.com/firmware/v3/demo_wcv3_4.36.8.26.zip
```

**Comment by dnestico** [comment]
@mrlt8 Just wondering, so I was reading the forums and some people said they had very little success when downloading timplapse videos when they switched to the RTSP firmware but almost none on the normal firmware.

Does the RTSP firmware include boa server or no? If it doesn't then oh well for me since my V3s are currently using RTSP firmware and my V2s will too since I managed to download the files before wyze removed them.

**Comment by mrlt8** [comment]
There are some references to boa in the rtsp iCamera:
```
➜  v3_rtsp strings iCamera|grep boa
productservices/localstorage/timelapseboa.c
(%s) kill boa, timeNow:%ld, killTime:%ld
killall -9 boa
killall -9 boa  
/usr/boa/boa  
(%s) boa already off!
boaKiller
(%s) boa timer add fail, tmpId:%d
(%s) boa timer add ok, tmpId:%d
time_lapse_boa_open
time_lapse_boa_open
time_lapse_boa_save_alive
time_lapse_boa_save_alive
time_lapse_boa_close
time_lapse_boa_close
time_lapse_boa_init
(%s) boa init fail!
protocol_time_lapse_boa_server_func
```

**Comment by JochenKlenk** [comment]
Hi so I tested v4.36.8.26 on one cam and that also not work. Boa URL is NONE. Also I get some new errors now.

-
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
2022/07/19 10:33:50 [WyzeBridge] 172.30.32.2 - - [19/Jul/2022 10:33:50] "GET /snapshot/haustuer.jpg?1658219629285= HTTP/1.1" 304 -
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 7, in <module>
    from datetime import datetime as dt
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode

Thanks

**Comment by mrlt8** [comment]
Could you run with `DEBUG_LEVEL=debug` and see if you can find the line around "Getting 120kb/s HD stream" where it shows something like:
```
{'status': '1', 'capacity': '30509', 'free': '2006'}
```

**Comment by JochenKlenk** [comment]
2022/07/20 09:55:42 [RTSP][TERRASSE] ✅ '/terrasse' stream is UP! (3/3)
frame=    1 fps=1.0 q=-1.0 size=N/A time=00:00:02.00 bitrate=N/A speed=1.94x    
Output file #0 does not contain any stream
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 7, in <module>
    from datetime import datetime as dt
  File "/usr/local/lib/python3.10/datetime.py", line 1183, in <module>
frame=   26 fps= 17 q=-1.0 size=N/A time=00:00:03.26 bitrate=N/A speed=2.13x    
    class IsoCalendarDate(tuple):
  File "/usr/local/lib/python3.10/datetime.py", line 1193, in IsoCalendarDate
    def week(self):
KeyboardInterrupt





time=00:00:30.60 bitrate=N/A speed=1.06x    
frame= 3937 fps= 20 q=-1.0 size=N/A time=00:03:18.84 bitrate=N/A speed=1.01x    
frame=  582 fps= 20 q=-1.0 size=N/A time=00:00:31.05 bitrate=N/A speed=1.06x    
frame= 3937 fps= 20 q=-1.0 size=N/A time=00:03:18.84 bitrate=N/A speed=   1x    
frame=  592 fps= 20 q=-1.0 size=N/A time=00:00:31.55 bitrate=N/A speed=1.06x    
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 5, in <module>
    import signal
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1615, in _fill_cache
KeyboardInterrupt





time=00:02:31.75 bitrate=N/A speed=1.01x    
frame= 6371 fps= 20 q=-1.0 size=N/A time=00:05:20.51 bitrate=N/A speed=1.01x    
frame= 3006 fps= 20 q=-1.0 size=N/A time=00:02:32.25 bitrate=N/A speed=1.01x    
frame= 6380 fps= 20 q=-1.0 size=N/A time=00:05:20.96 bitrate=N/A speed=1.01x    
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 5, in <module>
    import signal
  File "/usr/local/lib/python3.10/signal.py", line 3, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/local/lib/python3.10/enum.py", line 814, in <module>
    class Flag(Enum):
  File "/usr/local/lib/python3.10/enum.py", line 342, in __new__
    enum_class.__new__ = Enum.__new__
  File "/usr/local/lib/python3.10/enum.py", line 470, in __setattr__
    def __setattr__(cls, name, value):
KeyboardInterrupt

**Comment by exiva** [comment]
Is there any update on RDT to get web server and webhooks on latest wyze fw?

**Comment by mrlt8** [comment]
Still need to get the authentication working with the RDT_Client_Create() callback..
I believe the credentials are "admin" and the password is the ENR for the camera.

**Comment by dnestico** [comment]
Maybe the latest update fixed the boa server issue for some of the cameras 👀 

All of them are running RTSP firmware and as you can see 2 of them have the "SD card" button, although doesn't seem to do much so far unless that expected and only one of them actually works so far

<img width="1123" alt="Screen Shot 2022-08-25 at 1 07 15 PM" src="https://user-images.githubusercontent.com/3034555/186727083-277c23bd-7ef7-46ff-91a8-a895ffcc8845.png">

<img width="1012" alt="Screen Shot 2022-08-25 at 1 05 16 PM" src="https://user-images.githubusercontent.com/3034555/186726834-67f5701f-04dd-450b-ac21-c57502fcb4ea.png">

**Comment by mrlt8** [comment]
That's interesting, can you check the "sdParm" in the camera details? 
Boa info may also be missing from your Luna cam since it's not connected to the bridge.

I was originally planning to add the option to download/view all the recordings/alarms, but put that on pause since boa is missing on the newer firmware. You can read more about accessing the SD card over boa here: https://github.com/HclX/WyzeHacks/blob/master/info/http_server.md

**Comment by dnestico** [comment]
Just checked again now its only showing SD card option on the garage cam with that same white screen I sent before, here is what "sdParm" says:

**{ "capacity": "30420", "free": "1149", "status": "1" }**

<img width="255" alt="Screen Shot 2022-08-25 at 9 05 42 PM" src="https://user-images.githubusercontent.com/3034555/186794848-acb6c8e9-4e5a-45fa-9aed-662ee904ec7e.png">

<img width="1010" alt="Screen Shot 2022-08-25 at 9 06 06 PM" src="https://user-images.githubusercontent.com/3034555/186794885-7cb3eae7-f63a-427a-8b50-3f036c3b51bb.png">

**Comment by mrlt8** [comment]
The camera will kill the boa server after some time so that could be why it's not showing up. However, the bridge should attempt to restart it if it can't reach the boa server. 
If you check the logs, you should see something like `starting boa server`.

Boa is probably not showing up on your luna cam because you have on-demand enabled. Try streaming from the camera and refresh the page to see if it shows up.

As for the `SD Card` page, that's actually coming from the camera itself (notice the url is using the camera's IP address). You can navigate around by appending the folder name to the url. e.g. to view the record folder where all the recordings get stored:
```
http://<my.cam.i.p>/cgi-bin/hello.cgi?name=/record
```
To actually download stuff off the SD card, you'd need to use 
```
http://<my.cam.i.p>/SDPath/record/filename.mp4
```

**Comment by dnestico** [comment]
I went to stream from the camera but don't see "starting boa server" in the logs, I do see it for another camera though which shows the SD card button aka the garage one like before.

For the luna cam when I went to watch it live in the webview by clicking "HLS" the logs just said the usual client reading stuff.

As for the garage cam maybe the boa server is working good because the logs keep showing logs like this `"2022/08/25 23:01:45 [Garage Cam] Pulling photo file from camera (file_name='20220825_23_01_49.jpg')"`

And thanks, I will check out those folders soon.

**Comment by TristanBrotherton** [comment]
Hi there, is there a workaround for getting notification on movement with the wyze-cams on the latest firmware? I'm currently running wyze-bridge -> camera.ui to get HKSV in homekit. My goal is to be able to get motion alerts working. It seems the `MOTION_HTTP` URL never gets called as BOA is no longer included in the firmware?

**Comment by cheme75** [comment]
> Hi there, is there a workaround for getting notification on movement with the wyze-cams on the latest firmware? I'm currently running wyze-bridge -> camera.ui to get HKSV in homekit. My goal is to be able to get motion alerts working. It seems the `MOTION_HTTP` URL never gets called as BOA is no longer included in the firmware?

I initially tried the camera ui in homebridge but motion never worked for me. Now I’m using scrypted with the opencv motion plugin. It took some tweaking the plugin settings to dampen detection a bit for my cams since I was getting way to many for tree shadow motion, but I now get motion notifications closer to how I want from the home app.

**Comment by mrlt8** [comment]
Not yet. The camera doesn't seem to expose any motion flags, so one of our options is to try to use RDT, which is what I believe they're using to transfer the time lapse videos from the camera to the mobile app and check for new 'alarm' files that get created on motion, but  I'm still struggling to authenticate with the camera over RDT - I believe we need to use IOTC channel 10 with "admin" as the user and the ENR (parent ENR on the outdoor) as the password.

I believe the camera uses MQTT to publish motion to the app over AWS IOT Core, so if we could somehow connect to that, we'd be able to grab the motion events directly as well as make changes to the camera.

**Comment by dnestico** [comment]
It would be awesome if the motion events thing ever got figured out as I would 100% use those while since right now Im trying to train frigate to be more accurate and faster but haven't gotten it to the level wyzes person detection yet sadly.
