### ISSUE TITLE
Recording broken for Wyze Cam v2 Firmware 4.9.9.1433

### ISSUE THREAD

**Issue by pldimarco** [mrlt8/docker-wyze-bridge#575]
Hi, I have two wyze cam v2s. One is on 4.9.9.1433 and the other is on the previous 4.9.8.1002 firmware. I have recording set up and the older firmware works fine. The newer firmware creates the files but they're all 0 bytes. I don't see any errors in the logs. I am able to see the preview picture on the web ui.

**Comment by mrlt8** [comment]
There seems to be a weird bug with the recordings where it does the 0 bytes thing as we've had several reports of this from several users. I don't think it's related to the firmware version as it eventually starts working, but I will be trying to take another look.

**Comment by pldimarco** [comment]
Thanks @mrlt8! I can also grab more logs if there are additional flags to set to get `DEBUG` level logs.

**Comment by mrlt8** [comment]
`DEBUG_FFMPEG=True` would help.

**Comment by mrlt8** [comment]
Thank you! I was able to replicate the issue! I think it's related to the audio, so it is probably related to the firmware version after all!

The raw audio we're getting from the camera `pcm_mulaw` isn't supported in the mp4 container, so that's why it's failing to write the files. I think we'll either have to re-encode the audio or use another container like mov or mkv..

In the meantime, you can use `AUDIO_CODEC=AAC` which will force the bridge to re-encode the audio

**Comment by mrlt8** [comment]
@pldimarco  v1.8.12 should use the mov container if the audio is PCM and mp4 if AAC. 
Could you see if this fixes the issue for you?

**Comment by pldimarco** [comment]
@mrlt8 Tested `docker-wyze-bridge` with version `v1.8.12` against two Wyze Cam V2s with latest firmware, `4.9.9.1472`, and both are recording great. Thanks!
