### ISSUE TITLE
Reorder UI in Homeassistant add-on

### ISSUE THREAD

**Issue by jbeck22** [mrlt8/docker-wyze-bridge#650]
How do I reorder the UI when using the add-on through Homeassistant?

**Comment by mrlt8** [comment]
You should be able to drag and drop the cameras if you click and hold the title bar for each camera. 

An alternate way is to append a query parameter to the end of your request:

```
?order=front-cam,back-cam,garage,other
```

**Comment by bobpaul** [comment]
The URL param is awesome. And I noticed you don't have to put all the cams in the param; anything not mentioned will be sorted randomly.

Drag and drop isn't obvious, at least in firefox. I don't get the cursor change unless I'm on the far right side of the "title bar" portion of a cam:
![image](https://user-images.githubusercontent.com/90864/222478477-0f2bb573-cb07-416c-a6cb-30efc9b3366f.png)
![image](https://user-images.githubusercontent.com/90864/222478586-73472727-4144-41f7-8f14-b887e4d4cea5.png)

I think it's due to the `card-header-title` div.
![image](https://user-images.githubusercontent.com/90864/222478936-ef377859-ffab-44ba-b010-b2b44b51305d.png)

---

I love URL params and routes that add bookmark-ability to webapps, but when they're hidden they become useful only to a few. Do you think you could change the URL when we drag cameras? If I grab porch and put it in a position, then create the min `?order=...` and toss it up in the URL bar. Then people who stumble upon the drag and drop are also likely to spot the URL and either figure it out who to construct it themselves or at least know "oh, I can bookmark this to save my settings"

**Comment by mrlt8** [comment]
The clickable area should already be fixed in v2.0/dev branch.

I still want to improve the dragability on mobile, so I'll see if we can update the url at the same time.
