### ISSUE TITLE
question about wyze "still" shot generated automatically

### ISSUE THREAD

**Issue by cryptosmasher** [mrlt8/docker-wyze-bridge#734]
hello all, apologies my google fu has failed me on this - from what I can tell wyze automatically generates a still hosted on aws that references the last motion event, which is what displays in the app before streaming starts - am I understanding that correctly and is this image URL possible to get from docker-wyze-bridge ? from my reading it seems a high resolution image is generated upon start ? I saw pulling camera info shows a AWS image but this doesn't seem to update (?)  I know I can pull current an  I know I can use snapshot to get the current image? thanks

**Comment by mrlt8** [comment]
I believe the camera pushes a photo from the camera sensor (higher quality because it is taken before h264 compression) that gets pushed to the server for notification/object detection, so it probably only gets updated on motion events.

The AWS url is then returned with the list of the cameras from `https://api.wyzecam.com/app/v2/home_page/get_object_list`. However, the AWS url is pre-signed and expires after after about 20 min which is the reason we were only pulling the image on startup.

[V2 ](https://github.com/mrlt8/docker-wyze-bridge/pull/730) actually has a new `/thumb/cam-name.jpg` endpoint that will attempt to pull the latest "thumbnail" from the the api.

**Comment by cryptosmasher** [comment]
Is there a difference in quality that you know of vs the current snapshot functionality? Thanks

**Comment by mrlt8** [comment]
The "photos" taken on the camera will have more detail in them compared to the video snapshots as the photos are saved as image instead of being encoded to video with heavy h264 compression.

**Comment by cryptosmasher** [comment]
Ok I’ll give 2.0 dev builds a shot thank you

**Comment by cryptosmasher** [comment]
I fired up 2.0 to test this, thumb does show last event which is great, but it's def a lower resolution than "snapshot" - on the v3 ptz it's a 640 × 360 image

**Comment by cryptosmasher** [comment]
So def

**Comment by cryptosmasher** [comment]
So weird issue - I guess I have to cross reference with what the docker console says - I went into the wyze app for this camera (v3 ptz) not only did it take many retries to reconnect but it has a “2k” quality icon which when I clicked went to HD

**Comment by cryptosmasher** [comment]
no errors regarding this ptz camera but it's behaving very strangely connecting from the app until I kill bridge 2.0, I'll open a new issue if I can write it up with more info thanks
