### ISSUE TITLE
ERR no space left on device

### ISSUE THREAD

**Issue by PerpSearch** [mrlt8/docker-wyze-bridge#763]
This is most likely a me issue, but there's a chance some others will be equally unskilled.   I'm running a Syno DS218+ w/ more than enough ram and drive space.  Anyway, here's the portainer stack and log files and thanks for looking.

version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 6050:6050 # WEB-UI
        environment:
            - WYZE_EMAIL= XXXXXXXXXXXXXXX # Replace with wyze email 
            - WYZE_PASSWORD= XXXXXXXXXXX # Replace with wyze password
            - FILTER_NAMES=Zoom  

🚀 STARTING DOCKER-WYZE-BRIDGE v2.0.2

[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.0.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 🔐 MFA code Required
[WyzeBridge] 💬 SMS code requested
[WyzeBridge] 📝 Enter verification code in the WebUI or add it to /tokens/mfa_token.txt
[WyzeBridge] 🔑 Using 966189 for authentication
[WyzeBridge] ✅ Verification code accepted!
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 🪄 WHITELIST MODE ON [1/14]
[WyzeBridge] [+] Adding Zoom [WYZEC1-JZ]
[WyzeBridge] starting rtsp-simple-server v0.21.6
[WyzeBridge] 🎬 1 stream enabled
2023/04/03 02:39:41 ERR no space left on device
ice ERROR: 2023/04/03 02:39:41 could not read udp packet: read udp [::]:8189: use of closed network connection

**Comment by mrlt8** [comment]
Hmm, the error seems to be coming from the upstream rtsp-simple-server: https://github.com/aler9/mediamtx/discussions/376

**Comment by PerpSearch** [comment]
For another data point, I tried it w/ just 2 cams to see if I got a different result, one RTSP V2 and one stock V3.  I also did the Marius docker clean and prune, ran it again, and got the same error. I appreciate your checking.

**Comment by telnetdoogie** [comment]
I worked through this with @PerpSearch - This seemed to be caused by a limitation of file handles (or something similar) specific to the Synology NAS as a docker host, which I'd run into with other containers. 

The solution is to increase the `max_user_watches` and `max_user_instances` inotify settings on the synology. As that setting resets on reboot, users should set up a scheduled job that runs on boot to re-set these settings to higher values.

To change the settings one-time for testing, when logged into the synology host:

`sudo echo 204800 > /proc/sys/fs/inotify/max_user_watches`
`sudo echo 10000 > /proc/sys/fs/inotify/max_user_instances`

before or after, the set values can be observed with:

`sudo cat /proc/sys/fs/inotify/max_user_watches`
`sudo cat /proc/sys/fs/inotify/max_user_instances`

...capturing for posterity for those lucky Synology users that might run into the same issue.

**Comment by telnetdoogie** [comment]
If that change works for users, they can set up a scheduled job that runs as **root** on startup of the synology NAS with the following custom commands:

```bash
sh -c '(sleep 10 && echo 204800 > /proc/sys/fs/inotify/max_user_watches)&'

sh -c '(sleep 10 && echo 10000 > /proc/sys/fs/inotify/max_user_instances)&'
```

**Comment by PerpSearch** [comment]
> If that change works for users, 


I know you'll appreciate this, but I came here to do what you just did and make sure you're credited for the solution. Also, I use a different screen name on the Discord server.

Screwball2
